/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 30-lis-2021 16:58:34 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Adresa" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Atrakce" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Cipovakarta" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Kategorieatrakce" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Konto" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Ostatnisluzby" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "platba atrakce" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "platba ostani" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "pracuje" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Pristupovaprava" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Zakaznik" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Zamestnanec" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "Adresa"
(
	"Cp" VARCHAR(8) NULL,
	"Obec" VARCHAR(32) NULL,
	"Psc" CHAR(5) NULL,
	"Ulice" VARCHAR(32) NULL,
	"AdresaID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Atrakce"
(
	"Cena" NUMBER(8) NOT NULL,
	"Maximalnipocetzakazniku" NUMBER(3) NOT NULL,
	"Oteviracidoba" VARCHAR(16) NULL,
	"Oznaèeni" VARCHAR(32) NULL,
	"Popis" VARCHAR(64) NULL,
	"AtrakceID" NUMBER NOT NULL,
	"KategorieatrakceID" NUMBER NOT NULL
)
;

CREATE TABLE  "Cipovakarta"
(
	"Blokace" CHAR(1) NOT NULL,
	"Platnostkarty" DATE NULL,
	"CipovakartaID" NUMBER NOT NULL,
	"KontoID" NUMBER NOT NULL
)
;

CREATE TABLE  "Kategorieatrakce"
(
	"Nazev" VARCHAR(16) NOT NULL,
	"Popis" VARCHAR(16) NULL,
	"Vhodnyveknavstevniku" NUMBER(3) NULL,
	"KategorieatrakceID" NUMBER NOT NULL
)
;

CREATE TABLE  "Konto"
(
	"Datumzalozeni" DATE NOT NULL,
	"Platnostkonta" DATE NOT NULL,
	"Vlozenahotovost" NUMBER(6) NOT NULL,
	"KontoID" NUMBER NOT NULL,
	"ZakaznikID" NUMBER NOT NULL
)
;

CREATE TABLE  "Ostatnisluzby"
(
	"Cena" NUMBER(6) NOT NULL,
	"Oteviracidoba" VARCHAR(16) NOT NULL,
	"Oznaceni" VARCHAR(32) NOT NULL,
	"Popis" VARCHAR(64) NULL,
	"OstatnisluzbyID" NUMBER NOT NULL
)
;

CREATE TABLE  "platba atrakce"
(
	"AtrakceID" NUMBER NOT NULL,
	"CipovakartaID" NUMBER NOT NULL,
	"DATUM" DATE NOT NULL,
	"CENA" NUMBER(6) NOT NULL
)
;

CREATE TABLE  "platba_ostani"
(
	"OstatnisluzbyID" NUMBER NOT NULL,
	"CipovakartaID" NUMBER NOT NULL,
	"DATUM" DATE NOT NULL,
	"CENA" NUMBER(6) NOT NULL
)
;

CREATE TABLE  "pracuje"
(
	"AtrakceID" NUMBER NOT NULL,
	"DATUM OD" TIMESTAMP(9) NOT NULL,
	"ZamestnanecID" NUMBER NOT NULL,
	"DATUM DO" TIMESTAMP(9) NOT NULL
)
;

CREATE TABLE  "Pristupovaprava"
(
	"DatumDo" DATE NOT NULL,
	"DatumOd" DATE NOT NULL,
	"Seznamatrakci" NUMBER(3) NOT NULL,
	"PristupovapravaID" NUMBER NOT NULL,
	"ZamestnanecID" NUMBER NOT NULL,
	"AtrakceID" NUMBER NOT NULL
)
;

CREATE TABLE  "Zakaznik"
(
	"Jmeno" VARCHAR(16) NOT NULL,
	"Mail" VARCHAR(32) NOT NULL,
	"Prijmeni" VARCHAR(32) NOT NULL,
	"Telefon" VARCHAR(16) NOT NULL,
	"ZakaznikID" NUMBER NOT NULL,
	"AdresaID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Zamestnanec"
(
	"Email" VARCHAR(32) NULL,
	"Jmeno" VARCHAR(16) NOT NULL,
	"Prijmeni" VARCHAR(32) NOT NULL,
	"Primynadzrizeny" NUMBER NULL,
	"Rodnecislo" CHAR(10) NOT NULL,
	"Telefon" VARCHAR(16) NOT NULL,
	"ZamestnanecID" NUMBER NOT NULL,
	"CipovakartaID" NUMBER NOT NULL,
	"AdresaID" NUMBER NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "Adresa" 
 ADD CONSTRAINT "PK_Adresa"
	PRIMARY KEY ("AdresaID") 
 USING INDEX
;

ALTER TABLE  "Atrakce" 
 ADD CONSTRAINT "PK_Atrakce"
	PRIMARY KEY ("AtrakceID") 
 USING INDEX
;

ALTER TABLE  "Cipovakarta" 
 ADD CONSTRAINT "PK_Cipovakarta"
	PRIMARY KEY ("CipovakartaID") 
 USING INDEX
;

ALTER TABLE  "Kategorieatrakce" 
 ADD CONSTRAINT "PK_Kategorieatrakce"
	PRIMARY KEY ("KategorieatrakceID") 
 USING INDEX
;

ALTER TABLE  "Konto" 
 ADD CONSTRAINT "PK_Konto"
	PRIMARY KEY ("KontoID") 
 USING INDEX
;

ALTER TABLE  "Ostatnisluzby" 
 ADD CONSTRAINT "PK_Ostatnisluzby"
	PRIMARY KEY ("OstatnisluzbyID") 
 USING INDEX
;

ALTER TABLE  "Pristupovaprava" 
 ADD CONSTRAINT "PK_Pristupovaprava"
	PRIMARY KEY ("PristupovapravaID") 
 USING INDEX
;

ALTER TABLE  "Zakaznik" 
 ADD CONSTRAINT "PK_Zakaznik"
	PRIMARY KEY ("ZakaznikID") 
 USING INDEX
;

CREATE INDEX "IXFK_Zakaznik_Adresa"   
 ON  "Zakaznik" ("AdresaID") 
;

ALTER TABLE  "Zamestnanec" 
 ADD CONSTRAINT "PK_Zamestnanec"
	PRIMARY KEY ("ZamestnanecID") 
 USING INDEX
;

/* Create Foreign Key Constraints */

ALTER TABLE  "Atrakce" 
 ADD CONSTRAINT "FK_Atrakce_Kategorieatrakce"
	FOREIGN KEY ("KategorieatrakceID") REFERENCES  "Kategorieatrakce" ("KategorieatrakceID")
;

ALTER TABLE  "Cipovakarta" 
 ADD CONSTRAINT "FK_CipovaKarta_informace"
	FOREIGN KEY ("KontoID") REFERENCES  "Konto" ("KontoID")
;

ALTER TABLE  "Konto" 
 ADD CONSTRAINT "FK_Konto_uložení penìz"
	FOREIGN KEY ("ZakaznikID") REFERENCES  "Zakaznik" ("ZakaznikID")
;

ALTER TABLE  "platba atrakce" 
 ADD CONSTRAINT "FK_platí_Atrakce"
	FOREIGN KEY ("AtrakceID") REFERENCES  "Atrakce" ("AtrakceID")
;

ALTER TABLE  "platba atrakce" 
 ADD CONSTRAINT "FK_platí_CipovaKarta"
	FOREIGN KEY ("CipovakartaID") REFERENCES  "Cipovakarta" ("CipovakartaID")
;

ALTER TABLE  "platba_ostani" 
 ADD CONSTRAINT "FK_platí_OstatniSluzby"
	FOREIGN KEY ("OstatnisluzbyID") REFERENCES "Ostatnisluzby"   ("OstatnisluzbyID")
;

ALTER TABLE  "platba_ostani" 
 ADD CONSTRAINT "FK_platí_CipovaKarta"
	FOREIGN KEY ("CipovakartaID") REFERENCES "Ostatnisluzby"   ("OstatnisluzbyID")
;

ALTER TABLE  "platba_ostani" 
 ADD CONSTRAINT "FK_platba_OstatniSluzby"
	FOREIGN KEY ("OstatnisluzbyID") REFERENCES  "Ostatnisluzby" ("OstatnisluzbyID")
;

ALTER TABLE  "platba_ostani" 
 ADD CONSTRAINT "FK_platba_CipovaKarta"
	FOREIGN KEY ("CipovakartaID") REFERENCES  "Cipovakarta" ("CipovakartaID")
;

ALTER TABLE  "pracuje" 
 ADD CONSTRAINT "FK_pracuje_Atrakce"
	FOREIGN KEY ("AtrakceID") REFERENCES  "Atrakce" ("AtrakceID")
;

ALTER TABLE  "pracuje" 
 ADD CONSTRAINT "FK_pracuje_Zamestnanec"
	FOREIGN KEY ("ZamestnanecID") REFERENCES  "Zamestnanec" ("ZamestnanecID")
;

ALTER TABLE  "Pristupovaprava" 
 ADD CONSTRAINT "FK_PristupovaPrava_Zamestnanec"
	FOREIGN KEY ("ZamestnanecID") REFERENCES  "Zamestnanec" ("ZamestnanecID")
;

ALTER TABLE  "Pristupovaprava" 
 ADD CONSTRAINT "FK_PristupovaPrava_Atrakce"
	FOREIGN KEY ("AtrakceID") REFERENCES  "Atrakce" ("AtrakceID")
;

ALTER TABLE  "Zakaznik" 
 ADD CONSTRAINT "FK_Zakaznik_Adresa"
	FOREIGN KEY ("AdresaID") REFERENCES  "Adresa" ("AdresaID")
;

ALTER TABLE  "Zakaznik" 
 ADD CONSTRAINT "FK_Zakaznik_má"
	FOREIGN KEY ("AdresaID") REFERENCES  "Adresa" ("AdresaID")
;

ALTER TABLE  "Zamestnanec" 
 ADD CONSTRAINT "FK_Zamestnanec_vlastní"
	FOREIGN KEY ("CipovakartaID") REFERENCES  "Cipovakarta" ("CipovakartaID")
;
